### ISSUE TITLE
Docs feedback on Updating the App Manager

### ISSUE THREAD

**Issue by red-patience** [replicatedhq/replicated-docs#1077]
URL: https://docs.replicated.com/enterprise/updating-app-manager
Feedback details: I would expect this page to link to the page for installing the kots CLI. I'm told I have to upgrade the kots CLI to upgrade the App Manager, but it's a lot of clicks to find how to install the kots CLI if I don't have it yet.

**Comment by paigecalvert** [comment]
Thank you @red-patience ! You're absolutely right that this does not account for users who don't have the CLI installed yet. We'll make a story for this and report back.

**Comment by paigecalvert** [comment]
@red-patience we pushed some updates to this page to:
- clarify that the commands listed either install or update the kots CLI
- add a link to the kots CLI installation steps for more information

Could you take a look and let us know if this addresses your concern, or if additional updates would help? https://docs.replicated.com/enterprise/updating-app-manager#update-the-app-manager-in-existing-clusters

Thanks again!

**Comment by paigecalvert** [comment]
Going to close this out @red-patience, but of course feel free to open additional issues as needed!

**Comment by red-patience** [comment]
Thanks so much! Feels a lot clearer to me now.
