### ISSUE TITLE
Can't find airgap existing cluster tutorial

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#1100]
I need to do some local experimentation with airgapped existing-cluster installations, and I wanted to come back to this guide to get some steps to do the set up. 

https://github.com/replicatedhq/kots.io/blob/c27936a53aa6fa111f7a47036789be332f860fdd/content/vendor/guides/airgapped-existing-cluster.md

I couldn't find this anywhere in the site or in the repo. Is it still present in the docs.replicated.com site? I could perhaps see it being better suited for community or something, but I couldn't find it there either.

**Comment by paigecalvert** [comment]
Hey @dexhorthy, yeah you are correct that it was removed from the repo. I found the old story for it (https://app.shortcut.com/replicated/story/57807/redistribute-content-from-air-gap-quick-start-tutorial) and it looks like we redistributed the content from it to pull out the important info for vendors and enterprise users (if I recall, the idea was that the actual air gap docs were lacking and we wanted to pull the important from this tutorial). That said, I like your idea of moving it to community...I think at the time we just didn't think of that.

I'll make a story for the docs team to copy this tutorial content into the community site for easier reference in the future. Thank you for letting us know!
