### ISSUE TITLE
Docs updates for "All Customers" Page

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#1132]
URL: https://deploy-preview-1052--replicated-docs.netlify.app/vendor/licenses-about
Feedback details:

We should update the last header on here with a new screenshot and maybe a sentence or two about the instance detail that is displayed.

![Screenshot 2023-05-08 at 3 13 14 PM](https://user-images.githubusercontent.com/3730605/236924567-af52575c-6e49-4ea1-a8aa-e839150def87.png)

**Comment by paigecalvert** [comment]
Done as part of https://github.com/replicatedhq/replicated-docs/pull/1052
