### ISSUE TITLE
Docs feedback on helm-optional-charts

### ISSUE THREAD

**Issue by CharlesB2** [replicatedhq/replicated-docs#1181]
In step 3:

> Drag and drop the .tgz file into the file tree of the release. 

I don't want to do this since I'm developing on something not released yet. Alternative instructions for when a release isn't ready should be added

> For more information about adding Helm charts to a release in the vendor portal, see [Creating Releases with the Vendor Portal](https://docs.replicated.com/vendor/releases-creating-release)

This link is 404

**Comment by jonquil2002** [comment]
Hello, @CharlesB2.

Thank you so much for bringing these things to our attention. The link is now fixed.

Regarding the Helm chart alternative instructions, I'm checking with PM on that. I'm not sure, but it's possible that our new HelmChart v2 custom resource may solve that issue. You can see the preliminary docs here: https://deploy-preview-1189--replicated-docs-upgrade.netlify.app/reference/custom-resource-helmchart-v2

But we're still going to check directly and see if there is an alternative method. If so, we'll let you know. Please feel free to stay in communication with us.

**Comment by CharlesB2** [comment]
Yes I'm developing manifest files on something that isn't released

**Comment by paigecalvert** [comment]
Hi @CharlesB2 , I wanted to follow up on this issue as I see it's been open for a couple weeks now. In general, we recommend creating and promoting releases to the Unstable channel in the vendor portal when you are developing something that isn't ready to be released to customers yet (or to whatever channel your team uses for development). Unless one of your customers is assigned to a channel, they don't have access to any of the releases that you promote to that channel.

Though, that said, if this recommendation does not properly address your question, I recommend posting in https://community.replicated.com/ for help. This docs repo is not monitored by anyone outside of the docs team, so you might have better luck on the Community site :) I am going to close this out for now, though feel free to reopen as needed.
