### ISSUE TITLE
Docs feedback on replicated-cli-tokens

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#1192]
URL: https://docs.replicated.com/reference/replicated-cli-tokens
Feedback details:

The content on https://docs.replicated.com/reference/replicated-cli-tokens and https://docs.replicated.com/reference/vendor-api-using seems to have a lot of overlap, and serves almost the exact same purpose (help the user choose and create the right type of API token for their use case). The content for Vendor API V3 includes additional helpful information on token creation that should also be present in the CLI tokens guide. 

These guides should probably eventually share the same content.

**Comment by paigecalvert** [comment]
Thanks @dexhorthy, agreed. I made this story https://app.shortcut.com/replicated/story/78454

**Comment by paigecalvert** [comment]
Hi @dexhorthy , just merged these changes in https://github.com/replicatedhq/replicated-docs/pull/1348

The steps for generating tokens was moved to the Vendor Portal Teams and Accounts section, and both the replicated CLI and vendor API pages link to this new topic
