### ISSUE TITLE
Docs feedback on updating-embedded-cluster

### ISSUE THREAD

**Issue by barglee83** [replicatedhq/replicated-docs#1220]
URL: https://docs.replicated.com/enterprise/updating-embedded-cluster
Feedback details:

One thing that would be useful is guidance on how a Customer should do OS Level patching. We had a customer who ran some security updates on their VM which resulted in issues with the application. In terms of RCA one thing we identified was a lack of guidance on our side for the user to follow. 

A useful guide here could be something like:

Performing Host Level Upgrades
1. Check current status etc (get pods etc)
2. shutdown components (Not sure if this is recommended or we have a graceful application shutdown procedure)
3. run patching etc (whatever the VM operations needed)
4. reboot
5. check components are up

**Comment by paigecalvert** [comment]
Hi @barglee83 , thanks very much for sharing such detailed feedback. We somewhat recently updated the kURL open source docs site with procedures on how to perform host level updates: https://kurl.sh/docs/install-with-kurl/managing-nodes

This topic includes information about procedures like resetting nodes, rebooting nodes, removing nodes, and troubleshooting. Would you take a look and let me know if this addresses the use case that you're thinking?

The other thing I'm getting out of your feedback is that it might not be very useful that this content lives over on the kurl.sh open source site. It sounds like we either need to make sure that we are clearly linking to this content, or that we copy it over to docs.replicated.com

**Comment by barglee83** [comment]
Hey Paige, 
This is definitely really useful info - I hadn't thought to check the Kurl Pages.
Ill need to check out EKCO (I know this was recommended on another request)

Yeah I think it might be useful to link from Replicated to here

Barry
