### ISSUE TITLE
Docs feedback on 

### ISSUE THREAD

**Issue by rianfowler** [replicatedhq/replicated-docs#1228]
URL: https://docs.replicated.com/vendor/preflight-helm-defining
Feedback details:
- Recommend grouping these two sections. Maybe under "Input Kind" since you'll probably do one or the other. 
<img width="268" alt="Screenshot 2023-06-21 at 12 19 37" src="https://github.com/replicatedhq/replicated-docs/assets/4998130/12c62f10-0b72-4890-b947-0c32d395e78c">

**Comment by paigecalvert** [comment]
Good suggestion! I added this story for updating the organization accordingly: https://app.shortcut.com/replicated/story/80758/nest-create-custom-resource-and-create-secret-under-input-kind
