### ISSUE TITLE
I would like to know Replicated's plans for support of the Cloud-Native Computing Foundation going forward.  Specifically, plans to support the Internal Developer Experience trend and platform engineering.  I can be reached at: michael.kestigian@dxarcs.com.

### ISSUE THREAD

**Issue by MichaelBK223** [replicatedhq/replicated-docs#1251]
URL: 
Feedback details:

**Comment by jonquil2002** [comment]
@MichaelBK223  Hello, Michael. Thank you so much for your inquiry. I reached out to our product managers about your question and hope to have a response for you shortly.

**Comment by MichaelBK223** [comment]
Thank you so much for the quick and helpful reply.  So you know, there is
no near term urgency on this, and I know your teams are very busy.  I am
grateful for you getting back to me on this.

**Comment by AmberAlston** [comment]
@MichaelBK223  The question feels very broad, so I’m not sure I understand well enough what information you are specifically looking for, and for what purpose. 

Replicated has a several open source projects affiliated with the CNCF. Our KOTS and KURL projects that we maintain are reflected on their ecosystem landscape (https://landscape.cncf.io/?organization=replicated), and we’ve previously donated other projects like SchemaHero & ttl.sh to the larger community. 

The broader Replicated product is a unified platform that brings everything a commercial software vendor (ISV) needs to efficiently manage, distribute, install, and support their applications in their customers' environments. 

You can learn more about the capabilities of Replicated on the website, including trying it out for free - https://www.replicated.com/replicated-platform-overview. 

If you have a specific use case you want to see if Replicated can help support, the best course of action would be to request a demo on the website.

**Comment by MichaelBK223** [comment]
Thank you, I will check it out. Ànd your most helpful response is
appreciated.

**Comment by MichaelBK223** [comment]
Thank you for your help!
