### ISSUE TITLE
Docs feedback on helm-install-release

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#1304]
URL: https://docs.replicated.com/vendor/helm-install-release
Feedback details: May already be in the works, but just calling out need for updates as I'm reviewing Helm/SDK docs again

- No longer accurate. Entitlement is removed. "The Show Helm Install Tab feature flag must be enabled for your team in the vendor portal."
- Screenshot under Using the Vendor Portal, item 2, bullet 1, is outdated
- The workflow description under Using the Vendor Portal should be updated to match the new helm vs kots with helm modal and workflow ux. 

cc @dexhorthy as he may already be thinking about these changes as well given his team recently made these VP ux changes

**Comment by AmberAlston** [comment]
Same "Using the Vendor Portal" feedback here https://docs.replicated.com/vendor/replicated-sdk-using

**Comment by jonquil2002** [comment]
The entitlement is removed with PR https://github.com/replicatedhq/replicated-docs/pull/1318

The Using the Vendor Portal topics have all been addressed in this PR: https://github.com/replicatedhq/replicated-docs/pull/1309
