### ISSUE TITLE
Quirkiness with clicking Adding Resource Status Informers in the Nav

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#1307]
Until I caught what was happening I was very confused how I ended up back in Admin Console customization instead of Managing Resources and Objects. Loom showing the issue - https://www.loom.com/share/2944015ddf8b479283465f2ca4b56c8b

**Comment by jonquil2002** [comment]
SC: https://app.shortcut.com/replicated/story/84055/amber-issue-quirky-docusaurus-behavior-with-toc

**Comment by jonquil2002** [comment]
Fixed in https://github.com/replicatedhq/replicated-docs/pull/1315

Closing this PR.
