### ISSUE TITLE
Docs feedback on Adoption Report (Beta)

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#1308]
URL: https://docs.replicated.com/vendor/customer-adoption
Feedback details: This page calls out the feature as beta even though it's now GA. cc @dexhorthy

**Comment by jonquil2002** [comment]
I'm picking this up in SC: https://app.shortcut.com/replicated/story/84043/amber-issue-adoption-report-is-ga

**Comment by jonquil2002** [comment]
Fixed in PR https://github.com/replicatedhq/replicated-docs/pull/1313

Closing this PR
