### ISSUE TITLE
Docs feedback on Data transmission policy 

### ISSUE THREAD

**Issue by grantmiller** [replicatedhq/replicated-docs#1347]
URL: https://docs.replicated.com/vendor/policies-data-transmission
Feedback details: "Information about the installation (version of the app, version of Replicated components, version of Kubernetes, version of Kubernetes addons, and so on)." 

We should be specific about what "and so on" includes (as requested by a customer).

We should also include some information about what data is transferred TO the on-prem customer environment (manifests, release notes, images etc)

**Comment by paigecalvert** [comment]
Created a story for the Security team here: https://app.shortcut.com/replicated/story/84891

**Comment by paigecalvert** [comment]
Closing this out as the related story has been marked as Done
