### ISSUE TITLE
Docs feedback on custom-metrics

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#1469]
I'd love for this documentation to include a bit of the "why" behind the feature. I might get to this, but just want to track it somewhere - there's one sentence but it's buried in a paragraph, and I'd love to see a few use cases in bullet points that stand out a bit.

https://docs.google.com/document/d/1rqgVgxJ3llWDqkTDSfkcP1Gc4IA7bL3exWu8BLC001g/edit#heading=h.9b1ho9izxmes

I understand that we should be drawing a line between marketing materials and documentation, but I think this could use a nudge in the direction of "why" / "What's the value"

**Comment by paigecalvert** [comment]
Closing as I merged the related PR with updates to the "why". LMK if there's any additional updates you'd like to see there and I can open a new PR
