### ISSUE TITLE
Docs feedback on replicated-cli-completion-zsh

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#1470]
URL: https://docs.replicated.com/reference/replicated-cli-completion-zsh
Feedback details:

Trying to get this set up, the documentation and the inline `--help` feedback does not work.

![Screenshot 2023-09-26 at 3 36 41 PM](https://github.com/replicatedhq/replicated-docs/assets/3730605/f6a7cdf2-1336-4bae-892c-4052c8706c65)

Can we improve either the CLI-provided help or the documentation at docs.replicated.com to improve usability?

**Comment by dexhorthy** [comment]
FWIW i got this to work with `mkdir ~/.oh-my-zsh/custom/functions` - maybe we could expect a user would be able to figure that out.

**Comment by paigecalvert** [comment]
Hi @dexhorthy , could you expand on which part didn't work? Was this issue specifically for zsh? And for the `~/.oh-my-zsh/custom/functions` directory that you added, did you determine that that specific directory is required to enable shell completion in your environment?

Also, if the help in the CLI is also incorrect, this might be a story for the vendor exp team to update that CLI help accordingly and then ping me for the docs update (if my memory serves, I think that Siva might have added these docs)

**Comment by paigecalvert** [comment]
Closing. See https://replicated.slack.com/archives/CEEFDQURM/p1696355284694429?thread_ts=1696354524.661729&cid=CEEFDQURM for discussion
