### ISSUE TITLE
Docs feedback on kots-cli-admin-console-index

### ISSUE THREAD

**Issue by devbytyler** [replicatedhq/replicated-docs#1477]
URL: https://docs.replicated.com/reference/kots-cli-admin-console-index
Feedback details:

Hi! One of our customers had port-forwarding turned off in their cluster and they were accessing it via a jumphost (as a security requirement)

During a call with @crdant, the only way we could find a way to access the admin-console was by modifying the service to be a LoadBalancer and accessing it via the LoadBalancer's endpoint.

Would be nice to document a few alternative ways to access the admin-console in case port-forwarding is not an option. (Another method we attempted was a Socks Proxy)

**Comment by paigecalvert** [comment]
Thanks @devbytyler ! That does sound like something that should be documented. I'll follow up with @crdant to get more details

**Comment by paigecalvert** [comment]
(Finally) revisiting GitHub issues and I'm going to close this out as stale as we weren't able to prioritize it. This also strikes me as a subject that would lend itself well to an article on the Replicated Community site, if you are up for sharing the solution that you all and Chuck landed on: https://community.replicated.com/

Additionally, wanted to share this recently updated topic that explains how to expose services using NodePorts, and includes info about how the Admin Console is exposed as a NodePort during kURL/Embedded Cluster installations: https://docs.replicated.com/vendor/kurl-nodeport-services. Not strictly the same thing as this issue, but it does seem to provide some info in the same vein and figured it would be worth sharing.

Thanks again for sharing this feedback.
