### ISSUE TITLE
Kots and kURL section missing discoverable Airgap Content

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#1589]
URL: https://docs.replicated.com/vendor/releases-sharing-license-install-script
Feedback details: I'm writing a piece of content that needs a bit of an "about airgap installations" section, and I was looking for a docs page that I could link to. It seems that a lot of the airgap content for the kots/kurl installations is buried deep in sections that are not super intuitive. I think our docs, or at least the kots+kurl section of them, would benefit from a dedicated "about airgap" + "here's the different ways it applies if you're using replicated" section

<img width="332" alt="Screenshot 2023-11-03 at 4 49 36 PM" src="https://github.com/replicatedhq/replicated-docs/assets/3730605/86521845-91be-40f9-8d99-98586c8199a3">

<p><p>

<img width="329" alt="Screenshot 2023-11-03 at 4 49 25 PM" src="https://github.com/replicatedhq/replicated-docs/assets/3730605/aabc22f5-d3c3-4cc2-8b4c-e5074f32488a">

**Comment by paigecalvert** [comment]
I've had a similar thought in the past...When do you think the new content you're working will be ready to merge? I can either see about making a new section/topic quickly or also help find a place to put it in the meantime

**Comment by dexhorthy** [comment]
The content I'm working on is a blog post so it probably isn't docs-ready (I was hoping to avoid having to write it in the first place :joy:) -- the draft is here https://docs.google.com/document/d/1ixUbL5a7Cx21UZEcJreAD9H8BN4MpjA41K8SEjcklSg/edit

**Comment by paigecalvert** [comment]
Haha. Okay, cool. Well at the least, I can use the blog post when I write about air gapped telemetry. I also can still think about a more clear section on "supporting air gap installations". I added this story: https://app.shortcut.com/replicated/story/92894/create-section-where-vendors-can-easily-discover-content-about-how-to-support-air-gap-installs

Going to close this issue about as the story can become the source of truth for the need to update this
