### ISSUE TITLE
Docs feedback on private-images-replicated

### ISSUE THREAD

**Issue by sbihel** [replicatedhq/replicated-docs#1617]
URL: https://docs.replicated.com/vendor/private-images-replicated
Feedback details: When using `buildx` to build and push images to the Replicated registry, a 400 is returned due to the inclusion of [provenance attestations](https://docs.docker.com/build/attestations/slsa-provenance/). Adding support to the registry would be great but in the meantime it might be worth adding a note to disable provenance in the build (e.g. `--provenance=false` with the CLI).

**Comment by paigecalvert** [comment]
Thanks for the detailed feedback, @sbihel . Can do. I've shared this with the engineering team to make sure they are aware of this limitation and also to confirm if there are any related requirements that I might need to add as well.

**Comment by paigecalvert** [comment]
Hi @sbihel , reporting back that the topic was updated with the limitation about attestations; closing out this issue. Thanks again!
