### ISSUE TITLE
Docs feedback on preflight-defining

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#1794]
URL: https://docs.replicated.com/vendor/preflight-defining#check-kubernetes-distribution

I wasn't able to find a canonical list of what distributions might be returned in this function. For example, I have tested my app on `k3s`, and I'm wondering what the distribution string should be for k3s - I can of course guess, but could not find a list of possible distributions that might be returned. It was also not present here: https://troubleshoot.sh/docs/analyze/distribution/, another page which includes more and different example distros compared to the page on docs.replicated.com

**Comment by paigecalvert** [comment]
Thanks @dexhorthy ! I'll pass this along to the troubleshoot team and see if they can provide a full list. That would be certainly be helpful so users don't have to guess and check

**Comment by paigecalvert** [comment]
I have acquired the list and shall update the troubleshoot docs accordingly:

kurl
microk8s
aks
minikube
k3s
oke
rke2
dockerDesktop
digitalOcean
eks
gke
ibm

**Comment by paigecalvert** [comment]
Merged!
