### ISSUE TITLE
Annotations as strings (suggestion)

### ISSUE THREAD

**Issue by BRONSOLO** [replicatedhq/replicated-docs#2011]
https://docs.replicated.com/vendor/packaging-include-resources#requirements states: "The kots.io/exclude and kots.io/when annotations must be written in quotes (for example, "kots.io/exclude":). This is because Kubernetes annotations must be strings. For more information about working with Kubernetes annotations, see [Annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) in the Kubernetes documentation."

This is technically true for annotations in general but "kots.io/when" and "kots.io/exclude" are both valid strings without the quotes. Perhaps this section meant to say the `values` of these annotations must be strings?

**Comment by paigecalvert** [comment]
Thanks @BRONSOLO , I'll run this by the team
