### ISSUE TITLE
Docs feedback on installing-general-requirements

### ISSUE THREAD

**Issue by nate-credoai** [replicatedhq/replicated-docs#2076]
The Docker Hub requirement lists the domains at [Allowlist for Docker Desktop](https://docs.docker.com/desktop/allow-list/).  Is this really needed?  This is a pretty significant list and will be very difficult for our customers to manage with their network security team.

The Ask: please confirm that this information is current and actually required. Also, is there a way around this requirement?

**Comment by paigecalvert** [comment]
Thanks @nate-credoai -- I suspect you are right that not all of those are needed.

Just for context, it looks like that link to the docker desktop allowlist was added [here](https://github.com/replicatedhq/replicated-docs/pull/1593), and I was also able to find some context from the team discussion at the time surrounding the addition of that list of domains for docker desktop:

>And also maybe we should link to some upstream documentation from Dockerhub documenting what domains are needed. I found https://docs.docker.com/desktop/allow-list/ which is for Docker Desktop, **includes some domains a Vendor wouldn't care about**, but strangely omits [index.docker.io](http://index.docker.io/).

@diamonwiggins , curious for your opinion when you get the chance. We're currently telling vendors that all the domains listed on the allowlist for docker desktop are required, which I'm guessing is incorrect (see https://docs.replicated.com/enterprise/installing-general-requirements#firewall-openings-for-online-installations in the docs). Are there any domains on this allowlist that are truly required? If so, I'm thinking I could just list them out and/or list the ones that are _not_ required.

**Comment by paigecalvert** [comment]
Thanks Diamon! Agreed that listing cdn.auth0.com, *.docker.io, and *.docker.com is probably fine. I'll make these edits.

@nate-credoai let us know if this answers your question and/or if you have any follow-ups!

**Comment by nate-credoai** [comment]
Thank you. This will definitely make our lives easier with customers.
