### ISSUE TITLE
Docs feedback on customer-reporting

### ISSUE THREAD

**Issue by kayleemchugh** [replicatedhq/replicated-docs#2874]
URL: https://docs.replicated.com/vendor/customer-reporting
Feedback details:

Does this screenshot only show 1 instance, even though the supporting text above says it should be 2? 

<img width="943" alt="Screenshot 2024-12-04 at 1 23 24 PM" src="https://github.com/user-attachments/assets/46682347-c5d9-4d54-8224-05771ae44ea4">

**Comment by paigecalvert** [comment]
Indeed it does...the 'ol trick of updating a screenshot and forgetting to update the supporting text along with it
