### ISSUE TITLE
Docs feedback on replicated-cli-cluster-addon-create

### ISSUE THREAD

**Issue by sj-porter-knime** [replicatedhq/replicated-docs#2891]
URL: https://docs.replicated.com/reference/replicated-cli-cluster-addon-create
Feedback details:

Broken link ([replicated cluster addon create object-store](https://docs.replicated.com/reference/replicated-cli-addon-create-object-store))

**Comment by paigecalvert** [comment]
Thanks @sj-porter-knime ! And thanks @AmberAlston for the quick PR :)
