### ISSUE TITLE
Need to update RBAC link on SAML page

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#314]
The RBAC link on https://docs.replicated.com/vendor/team-management-saml-auth#role-based-access-control should go to the new RBAC content instead of the old help.replicated.com content

**Comment by AmberAlston** [comment]
@replicatedhq/replicated-docs FYI. I wanted to try out filing out an issue in the repo (^ this is valid). Did you get a notification before I added this comment?

**Comment by paigecalvert** [comment]
No, no notification until the comment. We also don't receive notifications on PRs unless we are added as reviewers

**Comment by AmberAlston** [comment]
@paigecalvert Looks like you can select "all" under watch, or just select certain events like new issues & prs. That may be an option for docs team members if we can't figure out a way to make that happen at a team level more automatically

**Comment by paigecalvert** [comment]
@AmberAlston nice, just updated my notification settings for issues and prs 👍

**Comment by paigecalvert** [comment]
Story for updating this link: https://app.shortcut.com/replicated/story/46779/update-rbac-link-to-point-to-docs-replicated-com

**Comment by paigecalvert** [comment]
@AmberAlston PR to update the RBAC link, if you can review and merge: https://github.com/replicatedhq/replicated-docs/pull/320

**Comment by AmberAlston** [comment]
Merged. Thanks! First issue closed!
