### ISSUE TITLE
"Built-in License Fields" documentation missing some fields

### ISSUE THREAD

**Issue by CxRP** [replicatedhq/replicated-docs#336]
The [About Built-in License Fields](https://docs.replicated.com/vendor/licenses-using-builtin-fields) documentation has a table of "Built-in License Fields". However, there are fields missing from the documentation:

- `channelID`
- `entitlements`
- `isSnapshotSupported`
- `isSupportBundleUploadSupported`

**Comment by AmberAlston** [comment]
@replicatedhq/replicated-docs

**Comment by paigecalvert** [comment]
Hi @CxRP , thanks for raising this. Just dropping in to let you know that I've added a story for this to our Docs team backlog, and I just picked it up. I will check back in when the story is complete to let you know that the additions are live on the docs site.

**Comment by paigecalvert** [comment]
Hi @CxRP, the previously-missing fields are now in the table in [About Built-In License Fields](https://docs.replicated.com/vendor/licenses-using-builtin-fields).

Also, the corresponding list of fields in the [License Context](https://docs.replicated.com/reference/template-functions-license-context) template functions topic was out of date as well, so I also updated that list in kind.

Thanks again!
