### ISSUE TITLE
Missing "how to uninstall kots CLI"

### ISSUE THREAD

**Issue by CxRP** [replicatedhq/replicated-docs#358]
The [Installing the kots CLI](https://docs.replicated.com/reference/kots-cli-getting-started) has information on how to **install** the kots CLI, but there is no documentation as to how to **remove/uninstall** the CLI.

_not to be confused with [remove an application using the kots CLI](https://docs.replicated.com/reference/kots-cli-remove)_

**Comment by paigecalvert** [comment]
Hi @CxRP!

I've been looking into this. For uninstalling the kots CLI itself, looks like it'll be: `sudo rm /usr/local/bin/kubectl-kots`

If you want to remove the KOTS components that were installed (this can be useful if you want to do a "clean slate" installation of the admin console and an application), you can run:
`kubectl delete ns <namespace>`
`kubectl delete clusterrole kotsadm-role`
`kubectl delete clusterrolebinding kotsadm-rolebinding`

I'm working on getting a story together about getting something into the docs on this, but wanted to share with you in the meantime.

**Comment by CxRP** [comment]
Thanks very much @paigecalvert !

**Comment by paigecalvert** [comment]
Hello again @CxRP ! Following up to let you know that the information about how to uninstall the kots CLI is live in the docs: https://docs.replicated.com/reference/kots-cli-getting-started#uninstall

Thanks again for the feedback 👍

**Comment by CxRP** [comment]
great. thanks for the update :-)
