### ISSUE TITLE
Docs feedback on snapshots-backup-hooks

### ISSUE THREAD

**Issue by MrSimonEmms** [replicatedhq/replicated-docs#518]
URL: https://docs.replicated.com/vendor/snapshots-backup-hooks
Feedback details:

Adding the [restore hooks](https://velero.io/docs/v1.9/restore-hooks) to the example would be extremely useful too

**Comment by paigecalvert** [comment]
Thank you @MrSimonEmms! I believe that we do have a story for this in our backlog. I will report back when we plan to pick it up.

**Comment by paigecalvert** [comment]
Okay, found that story that I mentioned. I am adding it to our queue for next week. Thanks for the help getting it prioritized!

**Comment by paigecalvert** [comment]
Hi @MrSimonEmms, I wanted to let you know that we've updated the topic to add a restore hook example & some additional high level info about restore hooks as well. Thank you again for providing this feedback; we appreciate hearing from you!
