### ISSUE TITLE
Docs feedback on custom-resource-config

### ISSUE THREAD

**Issue by sj-porter-knime** [replicatedhq/replicated-docs#529]
**As a** Replicated app dev trying to set up the config screen for my end users, **I want** to see screenshots/examples of what each Config item type looks like when rendered **so that** I don't have to try out several item types to understand how they are rendered or what would look best on the screen.

**Comment by paigecalvert** [comment]
Thank you for this feedback @sj-porter-knime.

I agree--I will add a story to our backlog to add screenshots to each item under the Examples heading (https://docs.replicated.com/reference/custom-resource-config#examples), and will report back shortly when we are able to pick it up!

Also, I know that this doesn't include all the item types and it sounds like you've already gone through the steps to manually test each one to see what it looks like, but I wanted to share this topic, which does have a few example screenshots: https://docs.replicated.com/vendor/admin-console-customize-config-screen#add-fields-to-the-configuration-screen.

**Comment by paigecalvert** [comment]
Hi @sj-porter-knime, just reporting back to let you know that there is an open PR for adding in these screenshots (#534). This is waiting on approval from a teammate so that we can get it merged.

**Comment by paigecalvert** [comment]
Hello again, #534 is merged, and the new screenshots are live. Thank you again for taking the time to share this feedback!
