### ISSUE TITLE
Docs feedback on kots CLI install reference

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#554]
URL: https://docs.replicated.com/reference/kots-cli-install#usage
Feedback details: This doesn't show default values for the flags, e.g. is `--copy-proxy-env` on by default?

**Comment by paigecalvert** [comment]
Thanks @dexhorthy . I created a story for this work here: https://app.shortcut.com/replicated/story/56888/all-flags-in-the-cli-reference-should-include-information-on-the-default

**Comment by paigecalvert** [comment]
If you happen to know any of the missing defaults offhand, we can add those in right away

**Comment by paigecalvert** [comment]
Here's the related story and PR for this:

https://app.shortcut.com/replicated/story/56888/all-flags-in-the-cli-reference-should-include-information-on-the-default

https://github.com/replicatedhq/replicated-docs/pull/599
