### ISSUE TITLE
Docs feedback on snapshots-creating

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#634]
2nd bullet on this page has a broken link

**Comment by paigecalvert** [comment]
Thank you! I think we noted 4 broken links total with this same typo in them. They should be fixed with the latest snapshots PR. Will follow up here to confirm. (cc @jonquil2002)

**Comment by paigecalvert** [comment]
With the above PR merged, I'm not seeing any broken links on the topic now (the content has also changed, so I think those might have been removed all together). https://docs.replicated.com/enterprise/snapshots-creating

Closing this out
