### ISSUE TITLE
Docs feedback on snapshots-creating

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#635]
"[Full Snapshots (recommended)](https://docs.replicated.com/enterprise/snapshots-creating#full-snapshots-recommended)." under https://docs.replicated.com/enterprise/snapshots-creating#partial link doesn't work

**Comment by paigecalvert** [comment]
Thanks Amber, this PR fixes the broken link if you'd like to merge! https://github.com/replicatedhq/replicated-docs/pull/641

(I left the other one that you mentioned in https://github.com/replicatedhq/replicated-docs/issues/634 to avoid a merge conflict with a PR that JQ has open that already addresses this)

**Comment by AmberAlston** [comment]
Sounds good. I've merged https://github.com/replicatedhq/replicated-docs/pull/641. Closing this issue.
