### ISSUE TITLE
 replicated-docs/docs/reference/kots-cli-install.md airgap links to 404 page

### ISSUE THREAD

**Issue by sprior** [replicatedhq/replicated-docs#647]
In the file  replicated-docs/docs/reference/kots-cli-install.md the --airgap and --airgap-bundle docs link to Installing in an Air Gapped Environment at 
https://github.com/replicatedhq/replicated-docs/blob/main/docs/enterprise/installing-existing-cluster#air-gap

which is a dead link.

**Comment by paigecalvert** [comment]
Hi @sprior , thanks for raising this. Those links appear to be working for me on the live docs site.

To attempt to recreate the issue, I went to https://docs.replicated.com/reference/kots-cli-install then clicked on the "[Installing in an Air Gapped Environment](https://docs.replicated.com/enterprise/installing-existing-cluster#air-gap)" links that appear in the `--airgap` and `--airgap-bundle` rows of the table.

For the github.com link that you shared above, I'm seeing that it is missing a `.md` after the filename. So, that should be https://github.com/replicatedhq/replicated-docs/blob/main/docs/enterprise/installing-existing-cluster.md.

To get to the correct anchor link in the GitHub preview, the full link would be: https://github.com/replicatedhq/replicated-docs/blob/main/docs/enterprise/installing-existing-cluster.md#install-in-an-air-gapped-environment-air-gap

Please let me know if this resolves the issue you are seeing, or let me know if I'm misunderstanding. 

Thanks!

**Comment by sprior** [comment]
What I was doing was to go to this github url:
https://github.com/replicatedhq/replicated-docs/blob/main/docs/reference/kots-cli-install.md

which renders the md file for reading, but the links I mentioned go to:
https://github.com/replicatedhq/replicated-docs/blob/main/docs/enterprise/installing-existing-cluster#air-gap

Yesterday when I first heard of your product I typed "replicated air gap" into Google and selected the first result which returned a 404 (which now appears to be fixed), so when I had trouble following links viewing in github I thought it might be a similar issue.

**Comment by paigecalvert** [comment]
Ah, understood. Thank you for that background @sprior. (And, sorry about the 404. That was my fault. We shuffled some content around recently, and I made a typo in the redirect that was supposed to handle that).

Just for context: The markdown files in this repo are rendered with our static site generator, Docusaurus, and published to docs.replicated.com. So, the links written in markdown in these files don't include the `.md` file extension that would be required for opening the file in the preview in this repo.

All said, good on you for tracking down the files in GitHub when you ran into that 404. I'm going to close this out as the links appear to be functioning correctly/as expected. Please keep us posted as you run into any other questions/requests/issues.
