### ISSUE TITLE
Docs feedback on 

### ISSUE THREAD

**Issue by mohansoundar-yb** [replicatedhq/replicated-docs#748]
URL: https://docs.replicated.com/
Feedback details: The hello world application link ( https://play.instruqt.com/replicated/tracks/hello-world ) is not available

**Comment by paigecalvert** [comment]
@mohansoundar-yb, thanks for letting us know! This Instruqt link slipped through the cracks (we did not intend to publish it). I'll be submitting a PR shortly to remove it.

In the meantime, if you are able to provision a Kubernetes cluster or a VM, you can take a look at this UI Tutorial in our docs, which will walk you through a similar hello world example: https://docs.replicated.com/vendor/tutorial-ui-setup

**Comment by paigecalvert** [comment]
PR to remove this broken link is merged--thanks again for providing this feedback.
