### ISSUE TITLE
Docs feedback on distributing-workflow

### ISSUE THREAD

**Issue by Jubke** [replicatedhq/replicated-docs#749]
URL: https://docs.replicated.com/vendor/distributing-workflow
Feedback details:

These three links under Prerequisites are broken:
 
[Managing Releases with the CLI](https://docs.replicated.com/vendor/tutorial-installing-with-cli).
[Packaging and Installing on an Existing Cluster](https://docs.replicated.com/vendor/tutorial-installing-with-existing-cluster).
[Packaging and Installing on a Kubernetes Installer Cluster](https://docs.replicated.com/vendor/tutorial-installing-without-existing-cluster).

**Comment by paigecalvert** [comment]
Thanks very much for letting us know, @Jubke. https://github.com/replicatedhq/replicated-docs/pull/750 to fix these links is merged
