### ISSUE TITLE
Docs feedback on gitops-workflow

### ISSUE THREAD

**Issue by Jubke** [replicatedhq/replicated-docs#794]
URL: https://docs.replicated.com/enterprise/gitops-workflow
Feedback details:

The GitOps documentation used to mention the limitation that the GitOps feature does not work with Helm charts. Removing this limitation triggered me to test it again... and it still doesn't work. Please add back the note or, even better, make it work with Helm! 😄

**Comment by paigecalvert** [comment]
Thank you @Jubke ! Good catch. We do see that the Helm/GitOps limitation is listed [over in the Helm section](https://docs.replicated.com/vendor/helm-installing-native-helm#native-helm-limitations), but it should certainly be listed in the GitOps topic that you linked as well.

We'll add a story to get that updated and report back.

**Comment by Jubke** [comment]
Ah, then that's probably where I saw it before...

**Comment by jonquil2002** [comment]
Hello, @Jubke. We finished making the update you requested. You can see it here: https://docs.replicated.com/enterprise/gitops-workflow

Thank you so much for letting us know!
