### ISSUE TITLE
Docs feedback on tutorial-ui-install-app-manager

### ISSUE THREAD

**Issue by seiya-nakayama** [replicatedhq/replicated-docs#825]
URL: https://docs.replicated.com/vendor/tutorial-ui-install-app-manager
Feedback details:

I tried to intall the App Manager in an Existing Cluster that is  EKS by AWS.

I installed KOTS in my local PC, and after I try to kots install my-test-app.
But, this error occured.

```
$ kubectl kots install ${my-test-app}/unstable
Enter the namespace to deploy to: ${my-test-app}
  • Deploying Admin Console
    • Creating namespace ✓  
    • Waiting for datastore to be ready ✓  
Error: Failed to deploy: failed to deploy admin console: failed to wait for rqlite: timeout waiting for statefulset to become ready. Use the --wait-duration flag to increase timeout.
```

I made sure my kubectl context is set to my existing cluster (EKS) as below
```
$ kubectl get svc

NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   172.20.0.1   <none>        443/TCP   73m
```

I adjusted the timeout time according to the error message and tried again, but the result was the same.
```
$ kubectl kots install ${my-test-app}/unstable --wait-duration 10m
Enter the namespace to deploy to: ${my-test-app}
  • Deploying Admin Console
    • Creating namespace ✓  
    • Waiting for datastore to be ready ✓  
Error: Failed to deploy: failed to deploy admin console: failed to wait for minio: timeout waiting for statefulset to become ready. Use the --wait-duration flag to increase timeout.
```

What should I do to fix this problem?

**Comment by paigecalvert** [comment]
Hi @seiya-nakayama , thanks for reaching out about this. Just for context: The Replicated Documentation team reviews the issues in this repo, so we are not always equip to help with troubleshooting issues with the product.

That said, one thing that comes to mind is that you could confirm that your existing cluster meets the minimum requirements as described here: https://docs.replicated.com/enterprise/installing-general-requirements#existing-cluster-requirements. In particular, the "Admin console minimum requirements" bullet point lists the disk space requirements for the admin console, including how much space is required for rqlite.

(I realize that we do not link to these requirements from the UI Tutorial, so you would not have been expected to find this on your own. We can be sure to update the UI Tutorial to add a link to these requirements.)

If that does not help, I recommend that you reach out to someone from your Replicated team for troubleshooting assistance. Or, I can help find someone who can provide additional guidance. Keep me posted.

**Comment by paigecalvert** [comment]
Hi @seiya-nakayama , just reporting back to let you know that we've updated the tutorials to include a link to the minimum system requirements for existing clusters. 

I am going to close out this issue for now, but feel free to reach back out if this was not the correct solution for the error message that you were receiving.
