### ISSUE TITLE
Docs feedback on custom-resource-lintconfig

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#835]
There's a broken link on this page -- `Linter Rules` links to `#linter-rules` but it looks like that was moved to another page maybe? https://docs.replicated.com/reference/custom-resource-lintconfig#linter-rules

**Comment by paigecalvert** [comment]
Thanks @dexhorthy ! PR to fix above: https://github.com/replicatedhq/replicated-docs/pull/837

**Comment by paigecalvert** [comment]
merged!

**Comment by dexhorthy** [comment]
woohoo!
