### ISSUE TITLE
Enterprise Docs: Updating Apps missing screenshots for configuring update interval

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#846]
This page: https://docs.replicated.com/enterprise/updating-apps#configure-automatic-updates is missing detail about how to configure upgrade interval and cadence (e.g. changing from "every 4 hours" to some other interval). The bullet points cover this, but I would have expected some screenshots.

**Comment by dexhorthy** [comment]
It would also be great if we documented our cron expression rules, or linked out to some generic cron docs

**Comment by jonquil2002** [comment]
Thanks @dexhorthy . I opened an SC to triage this and we'll circle back here to confirm when the work is done.

https://app.shortcut.com/replicated/stories/space/37255/documentation-team-view

**Comment by paigecalvert** [comment]
See duplicate issue here for additional details on this: https://github.com/replicatedhq/replicated-docs/issues/851

**Comment by paigecalvert** [comment]
The related PR to add more cron expression info is merged: https://github.com/replicatedhq/replicated-docs/pull/900

Circling back to close out this issue
