### ISSUE TITLE
Missing reference docs for nonexistent-status-informer-object Linter Rule

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#854]
URL: https://docs.replicated.com/reference/linter
Feedback details: my linter gave me this error, but this particular rule is not documented:

```
$ replicated release lint --yaml-dir=manifests
RULE                                  TYPE    FILENAME                   LINE    MESSAGE
nonexistent-status-informer-object    warn    manifests/kots-app.yaml    9       Status informer points to a nonexistent kubernetes object. If this is a Helm resource, this warning can be ignored.
```

**Comment by paigecalvert** [comment]
Forgot to circle back on this open issue, but the nonexistent-status-informer-object rule is now published here: https://docs.replicated.com/reference/linter#nonexistent-status-informer-object

PR that made this update: https://github.com/replicatedhq/replicated-docs/pull/855
