### ISSUE TITLE
Docs feedback on support-host-support-bundles

### ISSUE THREAD

**Issue by grahamnscp** [replicatedhq/replicated-docs#862]
URL: https://docs.replicated.com/vendor/support-host-support-bundles
Feedback details:

Hi 👋 
Noticed that this doc page has a dead link, https://docs.replicated.com/vendor/troubleshooting-an-app#generate-a-host-support-bundle
Best regards,
Graham

**Comment by jonquil2002** [comment]
Thanks, @grahamnscp . I'll fix it.

**Comment by grahamnscp** [comment]
Thank you :)

**Comment by jonquil2002** [comment]
Fixed and merged in this PR: https://github.com/replicatedhq/replicated-docs/pull/863

Closing. :)
