### ISSUE TITLE
Docs feedback on helm-optional-charts

### ISSUE THREAD

**Issue by CharlesB2** [replicatedhq/replicated-docs#868]
URL: https://docs.replicated.com/vendor/helm-optional-charts
Feedback details: 
`helm fetch stable/postgresl` this chart is obsolete, now it's bitnami.

**Comment by paigecalvert** [comment]
Thank you @CharlesB2! I made PR https://github.com/replicatedhq/replicated-docs/pull/872 to update the chart, and it's currently in technical review with the team.

**Comment by paigecalvert** [comment]
Hi @CharlesB2 -- PR #872 to address this issue is merged. Thanks again!
