### ISSUE TITLE
Docs feedback on K8s compatibility section 

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#882]
URL: https://docs.replicated.com/enterprise/installing-general-requirements#kubernetes-version-compatibility
Feedback details:

In https://docs.replicated.com/enterprise/installing-general-requirements#kubernetes-version-compatibility, the following pieces of content are outdated
* "Kubernetes versions 1.21 and earlier are end-of-life (EOL). " It's 1.22 and soon 1.23
* "Replicated recommends upgrading to a KOTS version that is compatible with Kubernetes 1.22 and higher." We should recommend 1.24 or higher
* The chart has not been updated as support for 1.25+ was added 
* On the note call out we should use a more recently example version number than 1.48

**Comment by jonquil2002** [comment]
Thanks for the feedback, @AmberAlston 

Created SC: https://app.shortcut.com/replicated/story/66535/update-k8s-version-compatibility-table

Will create PR to fix this and close the lop here when it is merged.

**Comment by jonquil2002** [comment]
Created PR: https://github.com/replicatedhq/replicated-docs/pull/885

**Comment by paigecalvert** [comment]
https://github.com/replicatedhq/replicated-docs/pull/885 merged!

More updates coming to this table as part of https://github.com/replicatedhq/replicated-docs/pull/699
