### ISSUE TITLE
Docs feedback on image-registry-airgap

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#895]
URL: https://docs.replicated.com/enterprise/image-registry-airgap
Feedback details: We're missing the instructions for using a BYO registry in online (non-airgap) scenarios, for either existing *or* embedded clusters.

The urgency on this isn't *crazy* high, but I am trying to advise a few vendors who rolled parts of this functionality themselves instead of using the kots built-in, and I'm realizing I don't have docs to send them on the usage of the "Registry" tab for online installs.

**Comment by dexhorthy** [comment]
cc @ajp-io

**Comment by ajp-io** [comment]
Yeah, I don't feel like this option was used a ton in the past, but I have also heard of a few vendors using a BYO registry for online installs recently (maybe Bugsnag). Agree it would be good to have.

I think @replicatedhq/replicated-docs works from Shortcut stories though, so they might want this there instead.

**Comment by paigecalvert** [comment]
We actually have this existing story, which I think covers the need: https://app.shortcut.com/replicated/story/55575/document-the-admin-console-registry-settings-tab

It's just kept getting overlooked in favor of higher priority stuff, but I can pull this over to the backlog. Probably about time

**Comment by jonquil2002** [comment]
@dexhorthy  Closing this PR because it looks like this work was completed in PR https://github.com/replicatedhq/replicated-docs/pull/925
