### ISSUE TITLE
Docs feedback on customer-reporting

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#949]
URL: https://docs.replicated.com/vendor/customer-reporting
Feedback details: Needs an updated screenshot

<img width="1151" alt="Screen Shot 2023-02-13 at 10 58 45 AM" src="https://user-images.githubusercontent.com/3730605/218522576-99ca3dbe-95a1-4f02-a005-3895a17234fa.png">

https://vendor.replicated.com/apps/wordpress-enterprise/customer/2JElWs7myGPAJYohPVeFnhEvebh/reporting

**Comment by paigecalvert** [comment]
Updated! https://github.com/replicatedhq/replicated-docs/pull/951
