### ISSUE TITLE
Docs feedback on trying to install the replicated cli using the curl command on a macos 

### ISSUE THREAD

**Issue by itsMarydan** [replicatedhq/replicated-docs#970]
URL: https://docs.replicated.com/reference/replicated-cli-installing
Feedback details: the installer tar does not work, it seems to be empty

**Comment by paigecalvert** [comment]
Thanks Mary, I'll ask the team about this. To clarify: were you running the [Mac](https://docs.replicated.com/reference/replicated-cli-installing#macos) or [Linux](https://docs.replicated.com/reference/replicated-cli-installing#linux) command on this page?

**Comment by paigecalvert** [comment]
Here's the error message I saw when I uninstalled and then tried to reinstall using the command. Is that what you saw as well?

```
tar: replicated: Not found in archive
tar: Error exit delayed from previous errors.
mv: rename replicated to /usr/local/bin/replicated: No such file or directory
```

**Comment by paigecalvert** [comment]
Hi again, just letting you know that I was able to speak with our engineering team about this error, and here is the reply that I received:

>looks like `amd64` should be `all`
>asset name for Mac was changed to `replicated_0.41.0_darwin_all.tar.gz` around the time M2 macs came out

I'll get this updated in the docs as soon as possible.

Thanks for letting us know!

**Comment by paigecalvert** [comment]
Closing this out as the fix has been merged, but feel free to open it back up if this does not address the issue for you.
