### ISSUE TITLE
Docs feedback on rn-whats-new

### ISSUE THREAD

**Issue by apbenn** [replicatedhq/replicated-docs#996]
URL: https://docs.replicated.com/release-notes/rn-whats-new
Feedback details:
The link for the App Manager "[Replicated Release Highlights blog](https://www.replicated.com/blog/tag/replicated%20release%20highlights/)" 404s. 

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/45721416/224716042-8c52be3d-6b5e-4a94-8243-da0126deb2e9.png">

**Comment by paigecalvert** [comment]
Thanks @apbenn ! Following up with the Marketing team to see if this link has changed: https://replicated.slack.com/archives/C0184BBC97W/p1678716624686429

**Comment by paigecalvert** [comment]
Fixed!
